language: ruby
rvm:
  - 2.3.0
cache: bundler
script:
  - bundle exec middleman deploy
env:
  global:
    - secure: "Td3wjO6zG/aJHBYrVDA2c8gpJj6rE9C8PFvlFS636es+4AV0HL3C8asFUmArFBE2D9ix1XtKKziOBygwdjKAqTXELYgCqXpqDzY4OhltWbYbkmu8nWQL7XxAfwsixdexSPoItOTOgkUUoLl72l74gWXZU0bKRYXXNf3q4F3xG7x3bjvRS514dxpJ46gVglNaedwV5WVPF1fBGYPwzr9gFvcyfmTZ2VyevSXLXXVfVRJf/i0TtetfGLdoH4MTunbNU1ltgxMmQ6ZZsOKX7pET3luH3Z9LF9eqbdojDiblGr8ERnY+dcdAJPm55PEQeNH1v9wWBjOnUc4Lg1hiJPIUKx7fUVpzqmo0XUQOERRLP0lO7J3y/j9GZE3B97RlQkDA7EUUR9gQ1mfAsIz1AbxMlXodrQzTdemdzVfGihEQLv0gH8o/LFMuXv6dFokJYJcDU4aq5UuNeOMxQ8TnQiRRuFHuBTtFsR5XKG41DimvP/bAiDjz8OLK5vNn1w5KkD5RnJNo/hpcLelUdfitVAjLam5+8WB2U77anDiiM7/LsFJ6hLqYc2zEyOMtRr4scte9b35z3groXC5SV3edimdwuxHhNBORiZmyUvfPtTp/TBoj/LEC6rwDqiL14WAqAr1WKUdcDtnAMMEL30H1CZZl08+aiMwBdpnJtdZE3DRfa70="
