language: ruby
rvm:
  - 2.3.0
cache: bundler
script:
  - git config --global user.name '${GIT_NAME}'
  - git config --global user.email '${GIT_NAME}'
  - git remote set-url origin https://julienpierremkg:${GH_TOKEN}@github.com/julienpierremkg/mkg-360.git
  - bundle exec middleman deploy
env:
  global:
    - secure: "ULSSpcG5M9As1TT+EC/hAB3q6gcpQXI0eFbJnJQMsFosx5ydXYPmCfbQTy7rk9rIuHtjZpWxKWBrpKiKpJjMEwyzm4Ip+brl1UYkKcMHwZD7ESVBDIzWkjM0c5imm6kKLtvNPx4G2+GrbjJHipjx2QJ6vTNrq64XmGyW/mP9Z3FuisncZXq1GoBpfM+7ISOPwOrC30+DiKqGQgpv5xpCrw97QsrFd6TTZPCDrd9U6lb7WgAcrY27kbH/kCNJf2UCE9Rlpw949R/xKJbIyxlxtFWnVWVJivkmka9SqSobtYL3n/XDJHuM3Da7p+/Vdd5sQLCA2gtZXC3e/tIi6cKO9bKKJw48YsD8/dK6IB8IstrkJGkdEzMymuuIjBHQgSsADCNs3Hfi9JBYUeAn6m66XQ4h/Fnx0DbJsiHLgNuoTKJgayu4i8TVUJIpHl/dDEg0zeqR2VYY2OiHanVjBIT5T7moqQxypdzkqPQbGaM40vv6mApEjBEWM+TfVSiX/P86ThGojlnx6jUotJHKXocUnWs5r4j24E7qTUByVfPa62KBZ7aRGjNjyR9wewUXLvEbO2f4v9cl6pJOSUpPFvIqZ72uc/DMsyb+vJNBf/DGiDM7oK5w9LZrrW0zydNt0VA6TQqwwWbkJAvX1ExFE30YEPBFJFiCbqnyuPpOi0WUuhM="
